### ISSUE TITLE
server - server.ts

### ISSUE THREAD

**Issue by Riley6639** [cernxavi/Next-Page#17]
set up an express server to handle incoming requests
include middleware if needed
listen on a specific port and establish a connection to the database

**Comment by Elementary-my-dear-Watson** [comment]
Worked on the server to handle incoming requests. Was able to get the server to listen on a specific port and establish a connection to the database.

**Comment by Riley6639** [comment]
server should be set up to listen on port 3000. it successfully starts and is able to be tested.
