### ISSUE TITLE
client - components - Nav.tsx

### ISSUE THREAD

**Issue by Riley6639** [cernxavi/Next-Page#3]
The navbar for our page
will have links to search, my books, browse, login
should be styled
when the links are clicked the router will take you too that page

**Comment by Elementary-my-dear-Watson** [comment]
planning on combining the Header into the Nav to help it be more seamless.

**Comment by Elementary-my-dear-Watson** [comment]
Did not combine the Nav with the Header. Ended up not making sense to do so.
