### ISSUE TITLE
client - components - Recommended.tsx

### ISSUE THREAD

**Issue by Riley6639** [cernxavi/Next-Page#6]
The element that contains a list of Recommended bookcards

**Comment by Elementary-my-dear-Watson** [comment]
Added basic code. Will need to change the style.

**Comment by Elementary-my-dear-Watson** [comment]
Also currently the  Recommended section is displayed with sample recommendations. We  can later replace the static data with dynamic data from an API or database.

**Comment by Elementary-my-dear-Watson** [comment]
Finished the code. Also the API is connected.
